[build-system]

requires = [
    "setuptools>=42",
    "wheel"
]

build-backend = "setuptools.build_meta"


[project]
name = "BL_Python"
requires-python = ">=3.10"
authors = [
    {name = 'Aaron Holmes', email = 'aholmes@mednet.ucla.edu'}
]
description = 'Python libraries for use in Boutros Lab.'
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU General Public License (GPL)",
    "Operating System :: OS Independent"
]
dynamic = ["version", "readme"]

[tool.setuptools.dynamic]
version = {attr = "BL_Python.__version__"}
readme = {file = ["README.md"], content-type = "text/markdown"}

[tool.setuptools.package-dir]
BL_Python = "BL_Python"

[tool.setuptools]
packages = ["BL_Python.web"]

dependencies = [
    "injector ~= 0.20",
#    "BL_Python.web"
]


[project.optional-dependencies]
web = [
    "BL_Python.web"
]
#aws = [
#    "boto3 ~= 1.27"
#]
#
#database = [
#    "sqlalchemy ~= 1.4",
#    "alembic ~= 1.8",
#    "sqlalchemy2-stubs ~= 0.0"
#]
#
#database-postgres = [
#    "psycopg2 ~= 2.9"
#]
#
#database-postgres-binary = [
#    "psycopg2-binary ~= 2.9"
#]
#
#web = [
#    "Flask == 1.1.4",
#    "flask-injector == 0.13.0",
#    "flask-login == 0.6.2",
#    "types-flask == 1.1.6",
#    "connexion == 2.14.2"
#    # specific version because Jinja (Flask dependency)
#    # does not specify an upper bound for MarkupSafe,
#    # and it pulls in a breaking change that prevents
#    # Flask from running.
#    "MarkupSafe == 1.1.1"
#]
#
#
dev-dependencies = [
    # testing automation. use specific versions so behavior does not change.
    "pytest == 7.4.0",
    "pytest-mock == 3.11.1",

    # code quality. allow minor version updates.
    # this can possibly change behavior of quality checks,
    # which allows us to catch new types of problems.
    "pyright ~= 1.1",
    "isort ~= 5.12",
    # specific version is nnecessary due to Flask dependency
    # version conflict with `click`
    # flask 1.1.4 depends on click<8.0 and >=5.1
    # black 22.1.0 depends on click>=8.0.0
    "black == 21.12b0",
]

#dev-static = [
#    "BL_Python[database-postgres-binary]"
#]
#
#dev-compiled = [
#    "BL_Python[database-postgres]"
#]
#
## use `all` for development
#all = [
#    "BL_Python[aws,database,web,dev-static,dev-dependencies]"
#]
#
[tool.pyright]
pythonVersion = "3.10"

include = [
    "*.py",
    "."
]

exclude = [
    ".venv",
    ".pytest_cache",
    ".github",
    ".git",
    "typings",
    "**/node_modules",
    "**/__pycache__"
]

stubPath = "./typings"

useLibraryCodeForTypes = true

typeCheckingMode = "strict"

reportImportCycles = "information"
reportCallInDefaultInitializer = "warning"
reportImplicitOverride = "information"
reportImplicitStringConcatenation = "warning"
reportMissingSuperCall = "information"
reportPropertyTypeMismatch = "error"
reportShadowedImports = "information"
reportUninitializedInstanceVariable = "information"
reportUnnecessaryTypeIgnoreComment = "information"
reportUnusedCallResult = "information"
reportMissingTypeStubs = "information"
