[build-system]

requires = [
    "setuptools>=42",
    "wheel"
]

build-backend = "setuptools.build_meta"

packages=['BL-python']

[project]
name = "BL-python"
version = "0.0.1"
dependencies = [
    "pyright == 1.1.316"
]