[build-system]

requires = [
    "setuptools>=42",
    "wheel"
]

build-backend = "setuptools.build_meta"

[project]
name = "BL_Python"
version = "0.0.1"
dependencies = [
    "pyright == 1.1.316"
]

[tool.setuptools.package-dir]
BL_Python = "BL_Python"