[build-system]

requires = [
    "setuptools>=42",
    "wheel"
]

build-backend = "setuptools.build_meta"

[project]
name = "BL-Python"
version = "0.0.1"
dependencies = [
    "pyright == 1.1.316"
]

[tool.setuptools]
platforms = ["any"]
packages=['BL_Python']