[build-system]

requires = [
    "setuptools>=42",
    "wheel"
]

build-backend = "setuptools.build_meta"

[project]
name = "BL_Python"
version = "0.0.1"

[tool.setuptools.package-dir]
BL_Python = "BL_Python"

[project.optional-dependencies]
dev = [
    "pyright == 1.1.316",
    "pytest == 7.4.0"
]

aws = [
    "boto3 ~= 1.27"
]