[build-system]

requires = [
    "setuptools>=42",
    "wheel"
]

build-backend = "setuptools.build_meta"


[project]
name = "BL_Python"
requires-python = ">=3.10"
authors = [
    {name = 'Aaron Holmes', email = 'aholmes@mednet.ucla.edu'}
]
description = 'Python libraries for use in Boutros Lab.'
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU General Public License (GPL)",
    "Operating System :: OS Independent"
]
dependencies = []

dynamic = ["version", "readme"]
[tool.setuptools.dynamic]
version = {attr = "BL_Python.__version__"}
readme = {file = ["README.md"], content-type = "text/markdown"}

[tool.setuptools.package-dir]
BL_Python = "BL_Python"

[tool.setuptools]
packages = [
    "BL_Python.AWS",
    "BL_Python.database",
    "BL_Python.development",
    "BL_Python.platform",
    "BL_Python.programming",
    "BL_Python.testing",
    "BL_Python.web"
]

[project.optional-dependencies]
AWS = [
    "BL_Python.AWS"
]
database = [
    "BL_Python.database"
]
development = [
    "BL_Python.development"
]
platform = [
    "BL_Python.platform"
]
programming = [
    "BL_Python.programming"
]
testing = [
    "BL_Python.testing"
]
web = [
    "BL_Python.web"
]
dev-dependencies = [
    # testing automation. use specific versions so behavior does not change.
    "pytest == 7.4.0",
    "pytest-mock == 3.11.1",

    # code quality. allow minor version updates.
    # this can possibly change behavior of quality checks,
    # which allows us to catch new types of problems.
    "pyright ~= 1.1",
    "isort ~= 5.12",
    # specific version is nnecessary due to Flask dependency
    # version conflict with `click`
    # flask 1.1.4 depends on click<8.0 and >=5.1
    # black 22.1.0 depends on click>=8.0.0
    "black == 21.12b0",
]

dev-static = [
    "BL_Python.database[database-postgres-binary]"
]
dev-compiled = [
    "BL_Python.database[database-postgres]"
]
## use `all` for development
all = [
    # libraries
    "BL_Python.AWS",
    "BL_Python.database",
    "BL_Python.development",
    "BL_Python.platform",
    "BL_Python.programming",
    "BL_Python.testing",
    "BL_Python.web",
    # development tools
    "BL_Python.dev-dependencies",
    "BL_Python.dev-static"
]

[tool.pyright]
pythonVersion = "3.10"

include = [
    "*.py",
    "."
]

exclude = [
    ".venv",
    ".pytest_cache",
    ".github",
    ".git",
    "typings",
    "**/node_modules",
    "**/__pycache__"
]

stubPath = "./typings"

useLibraryCodeForTypes = true

typeCheckingMode = "strict"

reportImportCycles = "information"
reportCallInDefaultInitializer = "warning"
reportImplicitOverride = "information"
reportImplicitStringConcatenation = "warning"
reportMissingSuperCall = "information"
reportPropertyTypeMismatch = "error"
reportShadowedImports = "information"
reportUninitializedInstanceVariable = "information"
reportUnnecessaryTypeIgnoreComment = "information"
reportUnusedCallResult = "information"
reportMissingTypeStubs = "information"
