[build-system]

requires = [
    "setuptools>=42",
    "wheel"
]

build-backend = "setuptools.build_meta"

[project]
name = "BL_Python.web"
requires-python = ">=3.10"
authors = [
    {name = 'Aaron Holmes', email = 'aholmes@mednet.ucla.edu'}
]
description = 'Libraries for building web applications in Boutros Lab.'
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU General Public License (GPL)",
    "Operating System :: OS Independent"
]

dependencies = [
    "BL_Python.programming == 0.0.1",

    "injector ~= 0.20",
    "Flask == 1.1.4",
    "flask-injector ~= 0.13.0",
    "flask-login == 0.6.2",
    "types-flask == 1.1.6",
    "connexion == 2.14.2",
    # specific version because Jinja (Flask dependency)
    # does not specify an upper bound for MarkupSafe,
    # and it pulls in a breaking change that prevents
    # Flask from running.
    "MarkupSafe == 1.1.1",
    "python-dotenv == 1.0.0",
    "json-logging == 1.3.0",
    "lib_programname == 2.0.9",
    "toml == 0.10.2",
    "pydantic ~= 2.1.1"
]

dynamic = ["version", "readme"]
[tool.setuptools.dynamic]
version = {attr = "BL_Python.web.__version__"}
readme = {file = ["README.md"], content-type = "text/markdown"}

[tool.setuptools.package-dir]
"BL_Python.web" = "BL_Python/web"

[tool.setuptools.packages]
find = {}

[project.optional-dependencies]
dev-dependencies = [
    "pytest == 7.4.0",
    "pytest-mock == 3.11.1",
    "mock == 5.1.0"
]