name: CICD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "**"
  workflow_dispatch:

jobs:
  All:
    name: Build and test BL_Python
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          ./install_all.sh

      - name: Test with pyright
        run: |
          pyright

      - name: Test with pytest and generate reports
        run: |
          echo Running pytest
          pytest \
            --cov='.' \
            --junitxml pytest.xml -o junit_family=xunit2 \
            -k "not acceptance"

          coverage html

      - name: Output pytest report
        uses: actions/upload-artifact@v3
        with:
          name: pytest-and-coverage-report
          path: |
            pytest.xml
            .coverage
            htmlcov/
          retention-days: 1
          if-no-files-found: error

      - name: Check code style
        run: |
          black --check src

      - name: Check import order
        run: |
          isort --check-only src
